#!/bin/bash
mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<-EOSQL
  CREATE DATABASE IF NOT EXISTS crm_db;
  CREATE DATABASE IF NOT EXISTS user_db;
  CREATE USER IF NOT EXISTS '$MYSQL_ADMIN_USER'@'%' IDENTIFIED BY '$MYSQL_ADMIN_PASSWORD';
  GRANT ALL PRIVILEGES ON crm_db.* TO '$MYSQL_ADMIN_USER'@'%';
  GRANT ALL PRIVILEGES ON user_db.* TO '$MYSQL_ADMIN_USER'@'%';
EOSQL
